/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.*;
import Model.*;
import Resources.Data;
import java.awt.BorderLayout;
import javax.swing.JPanel;

/**
 *
 * @author STEVEN.CARDONA
 */
public class GameView extends javax.swing.JPanel {

    /**
     * Creates new form GameView
     */
    public GameView(JPanel container, Player player, String topic) {
        initComponents();
        this.containerPanel = container;

        game = new Game(player, topic, Data.getWordList(topic));
        playerName.setText(game.getPlayer().getNombre());
        topicLabel.setText(game.getTopic());
        incompletedWordLabel.setText(game.getCurrent_word().getShow_word());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        playerName = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        failuresLabel = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        correctsLabels = new javax.swing.JLabel();
        attemps = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        incompletedWordLabel = new javax.swing.JLabel();
        buttonVowel_A = new javax.swing.JButton();
        buttonVowel_E = new javax.swing.JButton();
        buttonVowel_I = new javax.swing.JButton();
        buttonVowel_O = new javax.swing.JButton();
        buttonVowel_U = new javax.swing.JButton();
        topicLabel = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setToolTipText("Juego");
        setMaximumSize(new java.awt.Dimension(800, 450));
        setMinimumSize(new java.awt.Dimension(800, 450));
        setPreferredSize(new java.awt.Dimension(800, 450));

        playerName.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("X");

        failuresLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        failuresLabel.setText("0");

        jLabel4.setText("✔");

        correctsLabels.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        correctsLabels.setText("0");

        attemps.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        attemps.setText("0");

        jPanel1.setBackground(new java.awt.Color(233, 233, 233));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 365, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 293, Short.MAX_VALUE)
        );

        incompletedWordLabel.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        incompletedWordLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        buttonVowel_A.setBackground(new java.awt.Color(232, 232, 232));
        buttonVowel_A.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        buttonVowel_A.setText("A");
        buttonVowel_A.setBorderPainted(false);
        buttonVowel_A.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonVowel_AActionPerformed(evt);
            }
        });

        buttonVowel_E.setBackground(new java.awt.Color(232, 232, 232));
        buttonVowel_E.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        buttonVowel_E.setText("E");
        buttonVowel_E.setBorderPainted(false);
        buttonVowel_E.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonVowel_EActionPerformed(evt);
            }
        });

        buttonVowel_I.setBackground(new java.awt.Color(232, 232, 232));
        buttonVowel_I.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        buttonVowel_I.setText("I");
        buttonVowel_I.setBorderPainted(false);
        buttonVowel_I.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonVowel_IActionPerformed(evt);
            }
        });

        buttonVowel_O.setBackground(new java.awt.Color(232, 232, 232));
        buttonVowel_O.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        buttonVowel_O.setText("O");
        buttonVowel_O.setBorderPainted(false);
        buttonVowel_O.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonVowel_OActionPerformed(evt);
            }
        });

        buttonVowel_U.setBackground(new java.awt.Color(232, 232, 232));
        buttonVowel_U.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        buttonVowel_U.setText("U");
        buttonVowel_U.setBorderPainted(false);
        buttonVowel_U.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonVowel_UActionPerformed(evt);
            }
        });

        topicLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(incompletedWordLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(buttonVowel_A)
                                .addGap(22, 22, 22)
                                .addComponent(buttonVowel_E)
                                .addGap(22, 22, 22)
                                .addComponent(buttonVowel_I, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(buttonVowel_O)
                                .addGap(18, 18, 18)
                                .addComponent(buttonVowel_U)
                                .addGap(0, 23, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(playerName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(failuresLabel)
                        .addGap(41, 41, 41)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(correctsLabels)
                        .addGap(41, 41, 41)
                        .addComponent(attemps)
                        .addGap(12, 12, 12)))
                .addGap(12, 12, 12))
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(topicLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(playerName)
                        .addComponent(jLabel2)
                        .addComponent(failuresLabel)
                        .addComponent(attemps))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(correctsLabels)
                        .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(63, 63, 63)
                .addComponent(topicLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(incompletedWordLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(96, 96, 96)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(buttonVowel_A)
                            .addComponent(buttonVowel_E)
                            .addComponent(buttonVowel_I)
                            .addComponent(buttonVowel_O)
                            .addComponent(buttonVowel_U)))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(47, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void buttonVowel_AActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonVowel_AActionPerformed
        // TODO add your handling code here:
        validateVowel("a");
    }//GEN-LAST:event_buttonVowel_AActionPerformed

    private void buttonVowel_UActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonVowel_UActionPerformed
        // TODO add your handling code here:
        validateVowel("u");
    }//GEN-LAST:event_buttonVowel_UActionPerformed

    private void buttonVowel_EActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonVowel_EActionPerformed
        // TODO add your handling code here:
        validateVowel("e");
    }//GEN-LAST:event_buttonVowel_EActionPerformed

    private void buttonVowel_IActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonVowel_IActionPerformed
        // TODO add your handling code here:
        validateVowel("i");
    }//GEN-LAST:event_buttonVowel_IActionPerformed

    private void buttonVowel_OActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonVowel_OActionPerformed
        // TODO add your handling code here:
        validateVowel("o");
    }//GEN-LAST:event_buttonVowel_OActionPerformed

    private void validateVowel(String vowel) {
        Attempt at = game.validateAttempt(vowel, game.getCurrent_word().getMissing_vowel());
        updateAttempts();
        game.addAttemp(at);

        if (at.getIs_correct()) {
            int finishGame = game.removeWord(game.getCurrent_word());
            
            System.out.println(finishGame);
        
            if (finishGame == 0) {
                EndView view = new EndView(containerPanel, game);
                view.setSize(800, 450);
                view.setLocation(0, 0);

                containerPanel.removeAll();
                containerPanel.add(view, BorderLayout.CENTER);
                containerPanel.revalidate();
                containerPanel.repaint();
            } else {
                incompletedWordLabel.setText(game.getCurrent_word().getShow_word());
            }
        }
    }

    public void updateAttempts() {
        attemps.setText(String.valueOf(game.getNumber_attemps()));
        correctsLabels.setText(String.valueOf(game.getNumber_corrects()));
        failuresLabel.setText(String.valueOf(game.getNumber_failures()));
    }

    private Game game;
    private JPanel containerPanel;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel attemps;
    private javax.swing.JButton buttonVowel_A;
    private javax.swing.JButton buttonVowel_E;
    private javax.swing.JButton buttonVowel_I;
    private javax.swing.JButton buttonVowel_O;
    private javax.swing.JButton buttonVowel_U;
    private javax.swing.JLabel correctsLabels;
    private javax.swing.JLabel failuresLabel;
    private javax.swing.JLabel incompletedWordLabel;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel playerName;
    private javax.swing.JLabel topicLabel;
    // End of variables declaration//GEN-END:variables
}
